---
site_title: "ISSA Rochester Chapter | Information Systems Security Association of Rochester, NY"
site.baseurl: '/'

summit_start_date: 2023-10-25
summit_end_date: 2023-10-26
summit_location: "Rochester Riverside Convention Center"
